# Deploys a payload to the server to get the latest data
name: Deploy to Docker

on:
  push:
    branches: [ master ]

jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7.9 
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Docker Login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Dockerize
        run: |
          cd src/
          discord_key='"${{ secrets.ERROR_DUMP }}"'
          echo "api_key = $discord_key" > discord_key.py
          mkdir api_keys
          cd api_keys
          cat_api_key='"${{ secrets.CAT_KEY }}"'
          stock_api='"${{ secrets.FINNHUB }}"'
          echo "api_key = $cat_api_key" > cat.py
          echo "api_key = $stock_api" > stock.py
          cd ../
          bot_token='"${{ secrets.BOT_TOKEN }}"'
          echo "BOT_TOKEN = $bot_token" > .env
          cd ../
          docker build --tag gerbot .
      - name: docker push
        env:
          REPO: ${{ secrets.REPO }}
        run: |
          docker tag gerbot $REPO
          docker push $REPO


      
        

          

